import { Router } from 'express';
import { Request, Response } from 'express';
import { categoriesController } from '../controllers/categories.controller';
import { ordersController } from '../controllers/orders.controller';
import { paymentsController } from '../controllers/payments.controller';
import { productsController } from '../controllers/products.controller';
import { projectsController } from '../controllers/projects.controller';
import { mediaController } from '../controllers/media.controller';
import { vendorRequestsController } from '../controllers/vendor-requests.controller';
import { requireAuth } from '../middlewares/requireAuth';
import { requireRole } from '../middlewares/requireRole';
import { requirePermission } from '../middlewares/requirePermission';
import { validateRequest } from '../middlewares/validate-request.middleware';
import { localImageUpload } from '../middlewares/local-upload.middleware';
import { authRouter } from './auth.routes';
import { requireAdmin } from '../middlewares/requireAdmin';
import { systemRouter } from './system.routes';
import { shippingController } from '../controllers/shipping.controller';
import { adminController } from '../controllers/admin.controller';
import { slidesController } from '../controllers/slides.controller';
import { currenciesController } from '../controllers/currencies.controller';
import { teamController } from '../controllers/team.controller';
import { User, Vendor, Setting } from '../models';
import { AuthContext } from '../middlewares/requireAuth';
import { whiteLabelController } from '../controllers/white-label.controller';

const listUsers = async (_req: Request, res: Response) => res.json({ success: true, data: await User.find().select('-passwordHash').sort({ createdAt: -1 }) });
const getCurrentUser = async (req: Request, res: Response) => {
  const auth = (req as Request & { auth: AuthContext }).auth;
  const user = await User.findById(auth.userId).select('-passwordHash');
  if (!user) return res.status(404).json({ success: false, message: 'User not found' });
  return res.json({ success: true, data: user });
};
const listVendors = async (_req: Request, res: Response) => res.json({ success: true, data: await Vendor.find().sort({ createdAt: -1 }) });
const publicSettingKeys = ['marketplaceName', 'defaultCurrency', 'defaultLanguage', 'primaryCountry', 'logo', 'favicon', 'supportContact', 'supportEmail', 'supportPhone', 'companyAddress', 'maintenanceMode', 'maintenanceMessage', 'maintenanceImage', 'socialLinks', 'seo', 'checkout', 'shipping', 'vendors', 'homepage'];
const publicSettings = async (_req: Request, res: Response) => {
  const rows = await Setting.find({ key: { $in: publicSettingKeys, $not: /(secret|password|mongodb|uri|token|api[_-]?key|jwt)/i } });
  return res.json({ success: true, data: Object.fromEntries(rows.map((row) => [row.key, row.value])) });
};

const validateProduct = (req: Request) => {
  const required = ['name', 'slug', 'description', 'price', 'currency', 'category', 'vendor', 'stock'];
  for (const field of required) if (req.body[field] === undefined || req.body[field] === '') return `Missing field: ${field}`;
  if (!['FCFA', 'XOF', 'USD', 'EUR', 'CAD', 'CNY'].includes(req.body.currency)) return 'Invalid currency';
  if (req.body.status && !['draft', 'active', 'archived'].includes(req.body.status)) return 'Invalid product status';
  if (!Number.isFinite(Number(req.body.price)) || Number(req.body.price) <= 0) return 'price must be greater than 0';
  if (!Number.isInteger(Number(req.body.stock)) || Number(req.body.stock) < 0) return 'stock must be a positive integer';
  if (req.body.images && !Array.isArray(req.body.images)) return 'images must be an array';
  return null;
};
const validateProductUpdate = (req: Request) => {
  if (req.body.currency && !['FCFA', 'XOF', 'USD', 'EUR', 'CAD', 'CNY'].includes(req.body.currency)) return 'Invalid currency';
  if (req.body.status && !['draft', 'active', 'archived'].includes(req.body.status)) return 'Invalid product status';
  if (req.body.price !== undefined && (!Number.isFinite(Number(req.body.price)) || Number(req.body.price) <= 0)) return 'price must be greater than 0';
  if (req.body.stock !== undefined && (!Number.isInteger(Number(req.body.stock)) || Number(req.body.stock) < 0)) return 'stock must be a positive integer';
  if (req.body.images && !Array.isArray(req.body.images)) return 'images must be an array';
  return null;
};
const validateProject = (req: Request) => (!req.body.title || !String(req.body.title).trim() ? 'title is required' : null);
const validateCategory = (req: Request) => {
  if (!req.body.name || !String(req.body.name).trim()) return 'Le nom de catégorie est obligatoire';
  if (!req.body.slug || !String(req.body.slug).trim()) return 'Le slug de catégorie est obligatoire';
  if (req.body.active !== undefined && typeof req.body.active !== 'boolean') return 'Le statut active doit être booléen';
  if (req.body.order !== undefined && !Number.isFinite(Number(req.body.order))) return 'L’ordre doit être un nombre';
  return null;
};
const validateCategoryUpdate = (req: Request) => {
  if (req.body.name !== undefined && !String(req.body.name).trim()) return 'Le nom de catégorie est obligatoire';
  if (req.body.slug !== undefined && !String(req.body.slug).trim()) return 'Le slug de catégorie est obligatoire';
  if (req.body.active !== undefined && typeof req.body.active !== 'boolean') return 'Le statut active doit être booléen';
  if (req.body.order !== undefined && !Number.isFinite(Number(req.body.order))) return 'L’ordre doit être un nombre';
  return null;
};
const validateVendorRequest = (req: Request) => (!req.body.businessName ? 'businessName is required' : null);
const validateOrder = (req: Request) => {
  if (!Array.isArray(req.body.items) || req.body.items.length === 0) return 'items must be a non-empty array';
  for (const item of req.body.items) {
    if (!item.productId || !/^[a-f\d]{24}$/i.test(String(item.productId))) return 'Each productId must be a valid ObjectId';
    if (!Number.isInteger(item.quantity) || item.quantity <= 0) return 'Each quantity must be a positive integer';
  }
  if (!req.body.address?.country || !req.body.address?.city || !req.body.address?.phone) return 'address.country, address.city and address.phone are required';
  if (!req.body.shippingOptionId) return 'shippingOptionId is required';
  if (!['cash_on_delivery', 'diapay'].includes(req.body.paymentMethod)) return 'Invalid paymentMethod';
  return null;
};

export const apiRouter = Router();
apiRouter.use('/v1/auth', authRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use(systemRouter);
apiRouter.use(['/admin', '/cms', '/dashboard'], requireAuth, requireAdmin);
apiRouter.get('/admin/dashboard', adminController.dashboard);
apiRouter.get('/admin/audit-logs/export', adminController.auditLogsExport);
apiRouter.get('/admin/audit-logs/:id', adminController.auditLogById);
apiRouter.get('/admin/audit-logs', adminController.auditLogs);
apiRouter.get('/admin/products', adminController.products);
apiRouter.get('/admin/users', adminController.users);
apiRouter.get('/admin/users/:id', adminController.userById);
apiRouter.put('/admin/users/:id/role', adminController.updateUserRole);
apiRouter.put('/admin/users/:id/status', adminController.updateUserStatus);
apiRouter.get('/admin/slides', slidesController.list);
apiRouter.get('/admin/slides/:id', slidesController.getById);
apiRouter.get('/v1/content/team', requireAuth, requireAdmin, teamController.list);
apiRouter.get('/v1/content/public/team', teamController.publicList);
apiRouter.post('/v1/content/team', requireAuth, requireAdmin, teamController.create);
apiRouter.patch('/v1/content/team/:id', requireAuth, requireAdmin, teamController.update);
apiRouter.put('/v1/content/team/:id', requireAuth, requireAdmin, teamController.update);
apiRouter.delete('/v1/content/team/:id', requireAuth, requireAdmin, teamController.remove);
apiRouter.get('/admin/categories', categoriesController.adminList);
apiRouter.post('/admin/slides', slidesController.create);
apiRouter.put('/admin/slides/:id', slidesController.update);
apiRouter.delete('/admin/slides/:id', slidesController.remove);
apiRouter.post('/admin/categories', validateRequest(validateCategory), categoriesController.create);
apiRouter.put('/admin/categories/:id', validateRequest(validateCategoryUpdate), categoriesController.update);
apiRouter.delete('/admin/categories/:id', categoriesController.remove);
apiRouter.get('/admin/orders', ordersController.list);
apiRouter.get('/admin/orders/:id/payment-status', ordersController.getPaymentStatus);
apiRouter.post('/admin/orders/:id/shipment', shippingController.create);
apiRouter.post('/admin/orders/:id/shipment/sync', shippingController.sync);
apiRouter.get('/admin/shipping', shippingController.adminConfig);
apiRouter.put('/admin/shipping', shippingController.updateAdminConfig);
apiRouter.get('/admin/orders/:id', ordersController.getById);
apiRouter.put('/admin/orders/:id/status', ordersController.updateStatus);
apiRouter.get('/admin/currencies', currenciesController.list);
apiRouter.post('/admin/currencies', currenciesController.create);
apiRouter.put('/admin/currencies/:id', currenciesController.update);
apiRouter.delete('/admin/currencies/:id', currenciesController.remove);
apiRouter.get('/admin/commissions', adminController.commissions);
apiRouter.put('/admin/commissions/default', adminController.updateDefaultCommission);
apiRouter.put('/admin/categories/:id/commission', adminController.updateCategoryCommission);
apiRouter.get('/admin/vendors', adminController.vendors);
apiRouter.get('/admin/vendors/:id', adminController.vendorById);
apiRouter.patch('/admin/vendors/:id', adminController.updateVendor);
apiRouter.get('/admin/vendors/:id/catalog', adminController.vendorCatalog);
apiRouter.get('/admin/vendors/:id/orders', adminController.vendorOrders);
apiRouter.get('/admin/vendors/:id/customers', adminController.vendorCustomers);
apiRouter.get('/admin/vendors/:id/analytics', adminController.vendorAnalytics);
apiRouter.get('/admin/vendors/:id/documents', adminController.vendorDocuments);
apiRouter.put('/admin/vendors/:id/commission', adminController.updateVendorCommission);
apiRouter.get('/admin/vendor-requests', vendorRequestsController.list);
apiRouter.get('/admin/vendor-requests/:id', vendorRequestsController.getById);
apiRouter.put('/admin/vendor-requests/:id/approve', vendorRequestsController.approve);
apiRouter.put('/admin/vendor-requests/:id/reject', vendorRequestsController.reject);
apiRouter.put('/admin/vendors/:id/status', adminController.updateVendorStatus);
apiRouter.get('/admin/settings', adminController.settings);
apiRouter.put('/admin/settings', adminController.updateSettings);
apiRouter.get('/analytics/overview', requireAuth, requireAdmin, adminController.analyticsOverview);
apiRouter.get('/analytics/sales', requireAuth, requireAdmin, adminController.analyticsSection);
apiRouter.get('/analytics/vendors', requireAuth, requireAdmin, adminController.analyticsSection);
apiRouter.get('/analytics/products', requireAuth, requireAdmin, adminController.analyticsSection);
apiRouter.get('/analytics/customers', requireAuth, requireAdmin, adminController.analyticsSection);
apiRouter.get('/audit-logs/export', requireAuth, requireAdmin, adminController.auditLogsExport);
apiRouter.get('/audit-logs/:id', requireAuth, requireAdmin, adminController.auditLogById);
apiRouter.get('/audit-logs', requireAuth, requireAdmin, adminController.auditLogs);
apiRouter.get('/settings', requireAuth, requireAdmin, adminController.settings);
apiRouter.patch('/settings', requireAuth, requireAdmin, adminController.updateSettings);
apiRouter.get('/users/me', requireAuth, getCurrentUser);
apiRouter.get('/users', requireAuth, requireAdmin, listUsers);
apiRouter.get('/vendors', listVendors);
apiRouter.get('/settings', publicSettings);
apiRouter.get('/currencies', currenciesController.publicList);
apiRouter.get('/products', productsController.list);
apiRouter.get('/products/export', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.productExport);
apiRouter.get('/products/:id', productsController.getByIdOrSlug);

apiRouter.get('/users/:id/audit-logs', requireAuth, requireAdmin, adminController.auditLogs);
apiRouter.patch('/users/:id', requireAuth, requireAdmin, adminController.updateUserStatus);
apiRouter.post('/users', requireAuth, requireAdmin, (_req: Request, res: Response) => res.status(501).json({ success: false, message: 'User creation endpoint is declared for CMS integration; persistence policy remains to implement.' }));
apiRouter.patch('/products/:id', requireAuth, requireRole('admin', 'vendor'), requirePermission('products:update'), validateRequest(validateProductUpdate), productsController.update);
apiRouter.get('/vendors/:id', requireAuth, requireRole('admin', 'vendor'), adminController.vendorById);
apiRouter.patch('/vendors/:id', requireAuth, requireRole('admin', 'vendor'), adminController.updateVendor);
apiRouter.get('/vendors/:id/catalog', requireAuth, requireRole('admin', 'vendor'), adminController.vendorCatalog);
apiRouter.get('/vendors/:id/orders', requireAuth, requireRole('admin', 'vendor'), adminController.vendorOrders);
apiRouter.get('/vendors/:id/customers', requireAuth, requireRole('admin', 'vendor'), adminController.vendorCustomers);
apiRouter.get('/vendors/:id/analytics', requireAuth, requireRole('admin', 'vendor'), adminController.vendorAnalytics);
apiRouter.get('/vendors/:id/documents', requireAuth, requireRole('admin', 'vendor'), adminController.vendorDocuments);
apiRouter.get('/vendors/:id/payouts', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.vendorPayouts);
apiRouter.post('/vendors/:id/payouts', requireAuth, requireAdmin, whiteLabelController.createVendorPayout);
apiRouter.patch('/vendors/:id/bank-details', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.updateBankDetails);
apiRouter.get('/vendors/:id/messaging', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.vendorMessaging);
apiRouter.post('/vendors/:id/messages', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.createVendorMessage);
apiRouter.get('/storefront/:vendor_id/config', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.getConfig);
apiRouter.put('/storefront/:vendor_id/config', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.putConfig);
apiRouter.get('/storefront/:vendor_id/pages/home', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.getHome);
apiRouter.put('/storefront/:vendor_id/pages/home', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.putHome);
apiRouter.post('/storefront/:vendor_id/domain', requireAuth, requireRole('admin', 'vendor'), whiteLabelController.postDomain);
apiRouter.get('/promotions', requireAuth, requireAdmin, whiteLabelController.promotions);
apiRouter.post('/promotions', requireAuth, requireAdmin, whiteLabelController.createPromotion);
apiRouter.get('/analytics/campaigns/:id', requireAuth, requireAdmin, whiteLabelController.campaignAnalytics);
apiRouter.get('/email-templates', requireAuth, requireAdmin, whiteLabelController.emailTemplates);
apiRouter.put('/email-templates/:id', requireAuth, requireAdmin, whiteLabelController.updateEmailTemplate);
apiRouter.get('/public/storefront/:domain', whiteLabelController.publicStorefront);
apiRouter.post('/public/orders', requireAuth, validateRequest(validateOrder), ordersController.create);
apiRouter.post('/public/returns/claim', (_req: Request, res: Response) => res.status(501).json({ success: false, message: 'Returns claim intake is documented but not yet implemented.' }));

apiRouter.post('/products', requireAuth, requireRole('admin', 'vendor'), requirePermission('products:create'), validateRequest(validateProduct), productsController.create);
apiRouter.put('/products/:id', requireAuth, requireRole('admin', 'vendor'), requirePermission('products:update'), validateRequest(validateProductUpdate), productsController.update);
apiRouter.delete('/products/:id', requireAuth, requireRole('admin', 'vendor'), requirePermission('products:delete'), productsController.remove);
apiRouter.get('/projects', projectsController.list);
apiRouter.get('/projects/:id', projectsController.getById);
apiRouter.post('/projects', requireAuth, requireRole('admin', 'vendor'), requirePermission('projects:create'), validateRequest(validateProject), projectsController.create);
apiRouter.put('/projects/:id', requireAuth, requireRole('admin', 'vendor'), requirePermission('projects:update'), projectsController.update);
apiRouter.delete('/projects/:id', requireAuth, requireRole('admin', 'vendor'), requirePermission('projects:delete'), projectsController.remove);
apiRouter.get('/media', requireAuth, requireAdmin, mediaController.list);
apiRouter.get('/media/:id', requireAuth, requireAdmin, mediaController.getById);
apiRouter.post('/media/url', requireAuth, requireAdmin, requirePermission('media:manage'), mediaController.createFromUrl);
apiRouter.post('/media/upload', requireAuth, requireAdmin, requirePermission('media:manage'), localImageUpload, mediaController.upload);
apiRouter.put('/media/:id', requireAuth, requireAdmin, requirePermission('media:manage'), mediaController.update);
apiRouter.delete('/media/:id', requireAuth, requireAdmin, requirePermission('media:manage'), mediaController.remove);
apiRouter.get('/slides', slidesController.list);
apiRouter.get('/slides/:id', slidesController.getById);
apiRouter.get('/categories', categoriesController.list);
apiRouter.post('/categories', requireAuth, requireAdmin, validateRequest(validateCategory), categoriesController.create);
apiRouter.put('/categories/:id', requireAuth, requireAdmin, validateRequest(validateCategoryUpdate), categoriesController.update);
apiRouter.delete('/categories/:id', requireAuth, requireAdmin, categoriesController.remove);
apiRouter.post('/vendor-requests', requireAuth, validateRequest(validateVendorRequest), vendorRequestsController.create);
apiRouter.get('/vendor-requests', requireAuth, requireAdmin, requirePermission('vendors:approve'), vendorRequestsController.list);
apiRouter.put('/vendor-requests/:id/approve', requireAuth, requireAdmin, requirePermission('vendors:approve'), vendorRequestsController.approve);
apiRouter.put('/vendor-requests/:id/reject', requireAuth, requireAdmin, requirePermission('vendors:approve'), vendorRequestsController.reject);
apiRouter.post('/orders', requireAuth, validateRequest(validateOrder), ordersController.create);
apiRouter.get('/orders', requireAuth, requirePermission('orders:read'), ordersController.list);
apiRouter.get('/orders/:id', requireAuth, requirePermission('orders:read'), ordersController.getById);
apiRouter.get('/orders/:id/payment-status', requireAuth, ordersController.getPaymentStatus);
apiRouter.put('/orders/:id/status', requireAuth, requirePermission('orders:update'), ordersController.updateStatus);
apiRouter.post('/payments/diapay/checkout-session', requireAuth, paymentsController.createDiapayCheckoutSession);
apiRouter.get('/payments/diapay/session/:sessionId', requireAuth, paymentsController.retrieveDiapaySession);
apiRouter.post('/payments/diapay/webhook', paymentsController.handleDiapayWebhook);
apiRouter.get('/shipments', requireAuth, shippingController.list);
apiRouter.post('/shipping/estimate', shippingController.estimate);
apiRouter.post('/shipping/diaexpress/webhook', shippingController.webhook);
apiRouter.post('/orders/:id/shipment', requireAuth, shippingController.create);
apiRouter.get('/orders/:id/shipment', requireAuth, shippingController.byOrder);
apiRouter.get('/shipments/:trackingNumber', requireAuth, shippingController.byTracking);
apiRouter.post('/orders/:id/shipment/sync', requireAuth, shippingController.sync);
