import crypto from 'crypto';
import { Request, Response } from 'express';
import { env } from '../config/env';
import { getAuth } from '../middlewares/requireAuth';
import { orderScope } from '../middlewares/resource-access';
import { Order } from '../models/order.model';
import { Shipment } from '../models/shipment.model';
import { diaexpressService, mapDiaExpressStatus } from '../services/diaexpress.service';

const orderStatusFor = (status: string) => status === 'delivered' ? 'delivered' : ['picked_up','in_transit','out_for_delivery'].includes(status) ? 'shipped' : status === 'cancelled' ? 'cancelled' : 'processing';
const update = async (shipment: any, status: any, raw: any, source: 'provider'|'sync', eventId?: string) => {
  shipment.status = status; shipment.providerPayload = raw; shipment.history.push({ eventId, status, source, message: raw.message, location: raw.location, occurredAt: raw.occurredAt || new Date() }); if (eventId) shipment.processedEventIds.push(eventId); await shipment.save(); await Order.findByIdAndUpdate(shipment.order, { shipmentStatus: status, status: orderStatusFor(status) }); return shipment;
};
export const shippingController = {
  async list(_req: Request, res: Response) { const data = await Shipment.find().populate('order').sort({ createdAt: -1 }); return res.json({ data }); },
  async estimate(req: Request, res: Response) { const data = await diaexpressService.estimateShipping(req.body); return res.json(data); },
  async create(req: Request, res: Response) { const order = await Order.findOne({ _id: req.params.id, ...orderScope(getAuth(req)!) }).populate('customer'); if (!order) return res.status(404).json({ message: 'Order not found' }); const existing = await Shipment.findOne({ order: order.id }); if (existing) return res.json({ success: true, data: existing, idempotent: true }); if (order.paymentProvider === 'diapay' && order.paymentStatus !== 'paid') return res.status(409).json({ message: 'Online payment must be confirmed before shipment creation' }); if (!order.address?.country || !order.address?.city || !order.address?.phone || !order.items.length) return res.status(409).json({ message: 'Shipping address and items are required' }); const created = await diaexpressService.createShipment(order); const shipment = await Shipment.create({ order: order.id, provider: 'diaexpress', ...created, providerPayload: created.raw, history: [{ status: created.status, source: 'system', message: 'Shipment created' }] }); order.shipmentStatus = created.status; order.status = 'processing'; await order.save(); return res.status(201).json({ success: true, data: shipment }); },
  async byOrder(req: Request, res: Response) { const order = await Order.findOne({ _id: req.params.id, ...orderScope(getAuth(req)!) }); if (!order) return res.status(404).json({ message: 'Order not found' }); const data = await Shipment.findOne({ order: order.id }); if (!data) return res.status(404).json({ message: 'Shipment not found' }); return res.json({ data }); },
  async byTracking(req: Request, res: Response) { const shipment = await Shipment.findOne({ trackingNumber: req.params.trackingNumber }); if (!shipment) return res.status(404).json({ message: 'Shipment not found' }); const order = await Order.findOne({ _id: shipment.order, ...orderScope(getAuth(req)!) }); if (!order) return res.status(403).json({ message: 'Forbidden' }); return res.json({ data: shipment }); },
  async sync(req: Request, res: Response) { const order = await Order.findOne({ _id: req.params.id, ...orderScope(getAuth(req)!) }); if (!order) return res.status(404).json({ message: 'Order not found' }); const shipment = await Shipment.findOne({ order: order.id }); if (!shipment?.trackingNumber) return res.status(404).json({ message: 'Shipment not found or tracking unavailable' }); const result = await diaexpressService.getShipmentStatus(shipment.trackingNumber); await update(shipment, result.status, result.raw, 'sync'); return res.json({ data: shipment }); },
  async webhook(req: Request, res: Response) { const signature = String(req.headers['x-diaexpress-signature'] || ''); const raw = (req as Request & { rawBody?: string }).rawBody || ''; if (!env.diaexpressWebhookSecret) return res.status(503).json({ message: 'Webhook unavailable' }); const expected = crypto.createHmac('sha256', env.diaexpressWebhookSecret).update(raw).digest('hex'); if (signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return res.status(401).json({ message: 'Invalid signature' }); const eventId = String(req.body.eventId || ''); const shipment = await Shipment.findOne({ $or: [{ providerShipmentId: req.body.shipmentId }, { trackingNumber: req.body.trackingNumber }] }).select('+processedEventIds'); if (!shipment) return res.status(404).json({ message: 'Shipment not found' }); if (eventId && shipment.processedEventIds.includes(eventId)) return res.json({ success: true, idempotent: true }); await update(shipment, mapDiaExpressStatus(req.body.status), req.body, 'provider', eventId || undefined); return res.json({ success: true }); },
};
